## DATA 601 Project-1
### Deadline: November 18, 2024, 23:59pm

### Instructions
The input_data folder has various csv files related to MD crash data, weather data, total drivers by state and state names.

- MD_Crash_report files are vehicle crash report data obtained from for https://opendata.maryland.gov. These include four data tables on accident crash reports, driver (person) data, emergency medical services (EMS) data, and vehicle data. All tables have a common ID feature called "Report Number". The data includes the following years and quarters:
    - [CY2017Q1](https://opendata.maryland.gov/Public-Safety/Maryland-Statewide-Vehicle-Crashes-CY2017-Quarter-/9886-wded) 
    - [CY2017Q2](https://opendata.maryland.gov/Public-Safety/Maryland-Statewide-Vehicle-Crashes-CY2017-Quarter-/wnvu-hisq)
    - [CY2017Q3](https://opendata.maryland.gov/Public-Safety/Maryland-Statewide-Vehicle-Crashes-CY2017-Quarter-/m6zc-qj6d)
    - [CY2017Q4](https://opendata.maryland.gov/Public-Safety/Maryland-Statewide-Vehicle-Crashes-CY2017-Quarter-/9tum-d4as)
- States_drivers.csv includes data on total drivers by state.
- States.json includes the state name and abbreviations in case it is needed.

Other documentation:
- Sample __State of Maryland Vehicle Accident Report__ is included in the file "maryland_accident_report.pdf" (source: https://www.nhtsa.gov/sites/nhtsa.gov/files/documents/maryland_0.pdf). This report has several codes that can be used to explain codes in the data.
- The __Maryland Cross Reference Document__ is included in the file "maryland_cross_reference_document.pdf" (source: https://www.nhtsa.gov/sites/nhtsa.gov/files/documents/maryland_cross_reference.pdf). This document may also provide some more details in the codes in the data.
- The __maryland county codes__ is included in the file "MD_County_Codes.pdf" (source: https://mde.maryland.gov/programs/Land/Documents/LeadFactSheets/LeadfsCountyCodes.pdf)

<br>
Document any assumptions that you do as part of a comment or a markdown cell were appropriate. Note that you may change the format of the project as long as the questions are answered.

### Question 1 (15 points)

Review the questions below to familiarize yourself with the task. After reviewing the questions review the data files of the MD_Crash_Reports of the project and determine if it is worth merging/concatenation/joining and document your reasoning on merging or not merging the crash datafiles that will be used. Question 1 and 2 may be combined for purposes of organizing the Project 1 Jupyter Notebook.

### Question 2 (15 points)
Use the .info(), .describe(), .hist() and sns.pairplot() functions to explore the data. Comment on any observations and identify any features that may be worth plotting and evaluating in more detail. (Note that the last question requires to develop a visualization).

In [1]:
import os
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
files_path = r"C:\Users\Kimia Kyvn\Downloads\Project1"
all_files = os.listdir(files_path)
selected_files = [f for f in all_files]

df_Crash_Data = pd.read_excel(os.path.join(files_path, selected_files[0])) 
df_Crash_EMS = pd.read_excel(os.path.join(files_path, selected_files[1])) 
df_Crash_Person = pd.read_excel(os.path.join(files_path, selected_files[2]))   
df_Crash_Person_ID = pd.read_excel(os.path.join(files_path, selected_files[3]))
df_Crash_Vehicle = pd.read_csv(os.path.join(files_path, selected_files[4]))

In [ ]:
#df_Crash_Person_ID.head()
#df_Crash_Person_ID['REPORT_NO'].duplicated().sum()

merged_df = pd.merge(df_Crash_Person, df_Crash_Person_ID, on="id", how="inner")

In [6]:
df_Crash_Vehicle.head()

,HARM_EVENT_CODE,CONTI_DIRECTION_CODE,DAMAGE_CODE,MOVEMENT_CODE,REPORT_NO,CV_BODY_TYPE_CODE,VEH_YEAR,VEH_MAKE,COMMERCIAL_FLAG,VEH_MODEL,HZM_NUM,TOWED_AWAY_FLAG,GOING_DIRECTION_CODE,BODY_TYPE_CODE,DRIVERLESS_FLAG,FIRE_FLAG,PARKED_FLAG,SPEED_LIMIT,HIT_AND_RUN_FLAG,HAZMAT_SPILL_FLAG,VEHICLE_ID,TOWED_VEHICLE_CONFIG_CODE,AREA_DAMAGED_CODE_IMP1,AREA_DAMAGED_CODE1,AREA_DAMAGED_CODE2,AREA_DAMAGED_CODE3,AREA_DAMAGED_CODE_MAIN
0,1.0,S,4,13.0,AC1835001Z,NaN,2006.0,HYUNDAI,N,ELANTRA,NaN,Y,E,2.0,N,N,N,10,N,NaN,000004a9-960a-465e-af6c-a2c84781bac0,0,11.0,10.0,11.0,11.0,11.0
1,9.0,S,2,1.0,FP0147000L,NaN,2003.0,FORD,N,VAN,NaN,Y,S,21.0,N,N,N,25,N,NaN,000058c1-7e22-405c-91ec-73ac3e7e5e31,0,12.0,11.0,12.0,NaN,11.0
2,1.0,S,4,1.0,ADJ815000B,NaN,2007.0,DODGE,N,GRAND CARAVAN,NaN,Y,S,2.0,N,N,N,30,N,NaN,00006998-7357-458a-a0df-486d36c115c9,0,11.0,11.0,12.0,NaN,11.0
3,1.0,S,3,3.0,MSP5976004M,NaN,2013.0,HYUNDAI,N,PC,NaN,Y,S,2.0,N,NaN,N,50,N,NaN,00008008-4d5c-45a8-88cb-55aab6dd685e,0,6.0,6.0,NaN,NaN,6.0
4,1.0,W,3,2.0,MCP2966002P,1.0,2007.0,THOM,Y,BUS,NaN,N,W,12.0,N,N,N,40,N,U,0000da13-88d2-4376-8689-bb32dd2131a0,0,4.0,4.0,NaN,NaN,4.0

In [23]:
df_Crash_Person_ID[df_Crash_Person_ID.duplicated(subset=['REPORT_NO', 'PERSON_ID'], keep=False)]

,SEX_CODE,REPORT_NO,DATE_OF_BIRTH,PERSON_ID,LICENSE_STATE_CODE,VEHICLE_ID,EMS_UNIT_LABEL
155377,M,ADJ8420006,1974-12-15,19c44fb4-85f6-428d-a720-0ef28dbefd96,MD,b8ba3c58-4cf0-469a-a56e-03978222ed4f,NaN
170916,M,ADJ8420006,1974-12-15,19c44fb4-85f6-428d-a720-0ef28dbefd96,MD,NaN,NaN
247242,M,DA4089000F,1965-06-06,46ec4365-871f-4f53-9cc7-495627165142,NaN,76a1e099-74c6-4d01-ab72-68083cc3d183,NaN
247638,M,DA4089000F,1965-06-06,46ec4365-871f-4f53-9cc7-495627165142,NaN,NaN,A

In [4]:
df_Crash_Person_ID.head()

,SEX_CODE,REPORT_NO,DATE_OF_BIRTH,PERSON_ID,LICENSE_STATE_CODE,VEHICLE_ID,EMS_UNIT_LABEL
0,F,AA01140009,1966-03-21,39c8cf52-37a7-4ad1-83cf-ff7ae9dbf702,PA,ce98eb3c-abc4-465e-8850-00d4e7e9e89f,NaN
1,F,AACC50510003,1936-03-19,082d1a9d-1c75-46bc-a933-05295dada21b,MD,d76f575b-3a27-4b04-a400-18179e6fdc68,NaN
2,F,AB5468000D,1937-10-15,34062454-36d0-4329-8c5b-a49cacbc579c,MD,26ddba0a-a1b6-472e-a3af-922db4191c5c,NaN
3,F,AC1003000H,1995-03-26,73dfa504-0d90-48a6-b959-d404d78eb1f1,MD,f205b91d-d3f4-4b8b-b76d-ee31ea7e8eb1,NaN
4,F,AC1241000D,1966-06-05,1c2d0e2d-df36-486c-8b5f-d45072e1d6a2,MD,12ebb5af-4eee-4f41-b092-a9f98ee441b7,NaN

In [3]:
df_Crash_Person.head()

,SEX_CODE,CONDITION_CODE,INJ_SEVER_CODE,REPORT_NO,OCC_SEAT_POS_CODE,PED_VISIBLE_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,MOVEMENT_CODE,PERSON_TYPE,ALCOHOL_TEST_CODE,ALCOHOL_TESTTYPE_CODE,DRUG_TEST_CODE,DRUG_TESTRESULT_CODE,BAC_CODE,FAULT_FLAG,EQUIP_PROB_CODE,SAF_EQUIP_CODE,EJECT_CODE,AIRBAG_DEPLOYED,DATE_OF_BIRTH,LICENSE_STATE_CODE,CLASS,CDL_FLAG,EMS_UNIT_LABEL
0,F,0.0,1,AA01140009,NaN,NaN,NaN,NaN,NaN,NaN,D,0.0,NaN,0.0,NaN,NaN,N,0.0,13.0,0.0,0.0,1966-03-21,PA,C,N,NaN
1,F,0.0,1,AACC50510003,NaN,NaN,NaN,NaN,NaN,NaN,D,0.0,NaN,0.0,NaN,NaN,Y,1.0,13.0,1.0,1.0,1936-03-19,MD,C,N,NaN
2,F,0.0,1,AB5468000D,NaN,NaN,NaN,NaN,NaN,NaN,D,0.0,NaN,0.0,NaN,NaN,Y,1.0,13.0,1.0,1.0,1937-10-15,MD,NaN,N,NaN
3,F,0.0,1,AC1003000H,NaN,NaN,NaN,NaN,NaN,NaN,D,0.0,NaN,0.0,NaN,NaN,U,1.0,13.0,1.0,3.0,1995-03-26,MD,C,N,NaN
4,F,0.0,1,AC1241000D,NaN,NaN,NaN,NaN,NaN,NaN,D,0.0,NaN,0.0,NaN,NaN,N,1.0,13.0,1.0,1.0,1966-06-05,MD,C,N,NaN

In [22]:
df_Crash_Person_ID_unique[df_Crash_Person_ID_unique.duplicated(subset=['REPORT_NO', 'PERSON_ID'], keep=False)]

,SEX_CODE,REPORT_NO,DATE_OF_BIRTH,PERSON_ID,LICENSE_STATE_CODE,VEHICLE_ID,EMS_UNIT_LABEL
155377,M,ADJ8420006,1974-12-15,19c44fb4-85f6-428d-a720-0ef28dbefd96,MD,b8ba3c58-4cf0-469a-a56e-03978222ed4f,NaN
170916,M,ADJ8420006,1974-12-15,19c44fb4-85f6-428d-a720-0ef28dbefd96,MD,NaN,NaN
247242,M,DA4089000F,1965-06-06,46ec4365-871f-4f53-9cc7-495627165142,NaN,76a1e099-74c6-4d01-ab72-68083cc3d183,NaN
247638,M,DA4089000F,1965-06-06,46ec4365-871f-4f53-9cc7-495627165142,NaN,NaN,A

Empty DataFrame
Columns: [SEX_CODE, REPORT_NO, DATE_OF_BIRTH, PERSON_ID, LICENSE_STATE_CODE, VEHICLE_ID, EMS_UNIT_LABEL]
Index: []

In [ ]:
df_Crash_Person.hist()
df_Crash_Person_ID.duplicated(subset=['REPORT_NO','VEHICLE_ID','PERSON_ID']).sum()
df_Crash_Person_ID_unique[df_Crash_Person_ID_unique.duplicated(subset=['REPORT_NO', 'VEHICLE_ID', 'PERSON_ID'], keep=False)]

In [12]:
df_Crash_Data = df_Crash_Data.drop_duplicates()
df_Crash_EMS = df_Crash_EMS.drop_duplicates()
df_Crash_Person = df_Crash_Person.drop_duplicates()
df_Crash_Person_ID = df_Crash_Person_ID.drop_duplicates()
df_Crash_Vehicle = df_Crash_Vehicle.drop_duplicates()

### Question 3 (15 points)
Clean the data as you seem necessary. For example, evaluate remove null or duplicate values. Note there may be features where it may be appropriate to have values that are null or duplicated values. Document your reasoning.

### Question 4 (15 points)
a. For each county, determine the average speed of accidents involving bicyclists. (Note: Take a look at the Sample Maryland Crash Report. Report provides a map of the codes including those involving other bicyclists.) <br>
b. Sort the list the sorted by average speed.

### Question 5 (15 points)
a. Determine the total number of crashes per "vehicle make". Sort the results in alphabetical order by vehicle make (e.g. Chevrolet, Ford, Honda, etc.). <br>
b. Determine average age of the car involved in these accidents for each "vehicle make".

### Question 6 (15 points)
a. Determine all the accidents that happened in a circle centered at (39.197753, -77.263303) with a radius of 5 km.<br>
b. Determine the number of accidents where the speed limit was above 51 miles per hour within the 5 km circle. <br>
c. Determine the number of accidents where the speed limit was below 41 miles per hour within the 5 km circle.  <br>
<br>
Hint: Please see the "P1_Helper_Distance_From_Coordinates.ipynb" that can be found in the Project1 folder.

### Question 7 (15 points)

Determine the number of drivers, who got in a car crash, from non-DMV states and list them by total drivers, female and male. Consollidate the final values in one dataframe. <br>
`St | Drivers | Female | Male ` <br>
`NY | 151034  | 101000 | 50034` <br>
`PA | 125131  | 105000 | 20131` <br>
...


b. Use the states drivers data from the states_drivers.csv to normalize the previous list with number of total drivers for each state. For example, there are 12 million drivers in NY, then the normalized numbers should be:
<br>
`St |  Drivers  | Normalized` <br>
`NY |  151034   | 1.26E-5   ` <br>
`PA |  125131   |....       ` <br>
...

### Question 8 (15 points)
a. On which day of the week (Monday through Sunday) do the most of the crashes happen? <br>
b. On which hour of the day (00 - 24) do the most of the crashes happen?

### Question 9 (15 points)
a. What is the number of accidents that happened on rainy and clear/cloudy days?
b. What is the ration of the number of accidents that happened on rainy days to the number of accidents happened on clear/cloudy days? 
c. Calculate the number of fatal accidents that occur by each light condition.

What does these statistics tell us?

### Question 10 (10 points)
Use matplotlib and/or seaborn and show your talent in data visualization. You are free to visualize anything you want regarding this dataset.

# NOTEBOOK END